POST http://localhost:8081/realms/your-realm/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=your-client-id&grant_type=password&username=your-username&password=your-password

###
