spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/master

spring.kafka.bootstrap-servers=localhost:9092
app.kafka.topic.sensorData=sensor_records

spring.datasource.url=jdbc:postgresql://localhost:5432/test
spring.datasource.username=postgres
spring.datasource.password=admin