# 1. The URL expected in the token's "iss" claim (External URL)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/master

# 2. The URL Spring Boot actually calls to get the public keys (Internal URL)
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/master/protocol/openid-connect/certs

spring.kafka.bootstrap-servers=localhost:9092
app.kafka.topic.sensorData=sensor_records

spring.datasource.url=jdbc:postgresql://localhost:5432/test
spring.datasource.username=postgres
spring.datasource.password=admin