# 1. The URL expected in the token's "iss" claim (External URL)
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URL}/realms/master

# 2. The URL Spring Boot actually calls to get the public keys (Internal URL)
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_URL}/realms/master/protocol/openid-connect/certs

spring.kafka.bootstrap-servers=${KAFKA_URL}
app.kafka.topic.sensorData=${SENSOR_DATA_TOPIC}

spring.datasource.url=${SPRING_DB_URL}
spring.datasource.username=${SPRING_DB_USERNAME}
spring.datasource.password=${SPRING_DB_PASSWORD}