spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_URL}/realm/master

spring.kafka.bootstrap-servers=${KAFKA_URL}
app.kafka.topic.sensorData=${SENSOR_DATA_TOPIC}

spring.datasource.url=${SPRING_DB_URL}
spring.datasource.username=${SPRING_DB_USERNAME}
spring.datasource.password=${SPRING_DB_PASSWORD}